- name: Update yum packages
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: true
  become: true
  when:
    - ansible_os_family | lower == "redhat"
    - update_image
  tags:
    - skip_ansible_lint

- name: Update apt packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
  when:
    - ansible_os_family | lower == "debian"
    - update_image
  tags:
    - skip_ansible_lint
